import { generateSyntheticSnapshot } from "../src/synthetic-market";

const snapshot = generateSyntheticSnapshot();
const snapshotText = `${JSON.stringify(snapshot)}\n`;
const round = (value: number) => Math.round(value * 100) / 100;
const sourceBars = snapshot.bars.QQQ!;
const preview = sourceBars.flatMap((bar, index) => {
  if (bar.date < "2024-01-02" || bar.date > "2024-12-31") return [];
  const sma = sourceBars.slice(index - 119, index + 1).reduce((sum, item) => sum + item.close, 0) / 120;
  return [[bar.date, round(bar.open), round(bar.high), round(bar.low), round(bar.close), bar.volume, round(sma)]];
});
const source = {
  symbol: "QQQ",
  name: "Synthetic example",
  provider: "Strategy Court generator",
  mode: "Synthetic demo",
  interval: "Fictional weekday sessions",
  currency: "USD",
  adjustment: "None, generated values",
  startDate: "2024-01-02",
  endDate: "2024-12-31",
  fetchedAt: snapshot.fetchedAt,
  note: "Generated prices for an interface demo. Not actual QQQ prices or investment evidence.",
  snapshotId: snapshot.id,
};
const previewText = `// Generated by packages/fixtures/scripts/generate-synthetic-snapshot.ts.\n// Synthetic test values. No external prices, actual market calendar, or investment evidence.\nexport type LandingMarketBar = readonly [date: string, open: number, high: number, low: number, close: number, volume: number, sma120: number];\n\nexport const LANDING_MARKET_SOURCE = ${JSON.stringify(source, null, 2)} as const;\n\nexport const LANDING_MARKET_DATA: readonly LandingMarketBar[] = ${JSON.stringify(preview)};\n`;
const files = [
  [new URL("../market-data/synthetic-snapshot.json", import.meta.url), snapshotText],
  [new URL("../../../apps/web/src/data/syntheticLandingMarket.ts", import.meta.url), previewText],
] as const;
for (const [path, expected] of files) {
  if (process.argv.includes("--check")) {
    if (await Bun.file(path).text() !== expected) throw new Error(`Generated synthetic data is stale: ${path.pathname}`);
  } else {
    await Bun.write(path, expected);
  }
}
console.log(`Synthetic data ${process.argv.includes("--check") ? "verified" : "generated"}: ${snapshot.symbols.length} fictional sleeves, ${preview.length} preview bars. No network requests.`);
